return {
	-- executables you expect on PATH per language
	by_lang = {
		lua = { "stylua" },
		bash = { "shfmt" },
		python = { "isort", "black" },
		javascript = { "prettier" },
		typescript = { "prettier" },
		json = { "jq", "prettier" },
		toml = { "taplo" },
		yaml = { "yamlfmt" },
		sql = { "sqlfluff" },
		php = { "phpcbf" },
		c = { "clang-format" },
		cpp = { "clang-format" },
		rust = { "rustfmt" },
		html = { "prettier" },
		css = { "prettier" },
		markdown = { "prettier" },
		go = { "gofmt" },
		java = {},
		kotlin = {},
	},

	-- Conform mapping: executable -> conform formatter id + filetypes (when needed)
	mappings = {
		stylua = { conform = "stylua", filetypes = { "lua" } },
		shfmt = { conform = "shfmt", filetypes = { "sh", "bash" } },
		isort = { conform = "isort", filetypes = { "python" } },
		black = { conform = "black", filetypes = { "python" } },
		prettier = { conform = "prettier" },
		jq = { conform = "jq", filetypes = { "json" } },
		taplo = { conform = "taplo", filetypes = { "toml" } },
		yamlfmt = { conform = "yamlfmt", filetypes = { "yaml" } },
		sqlfluff = { conform = "sqlfluff", filetypes = { "sql" } },
		phpcbf = { conform = "phpcbf", filetypes = { "php" } },
		["clang-format"] = { conform = "clang-format", filetypes = { "c", "cpp" } },
		rustfmt = { conform = "rustfmt", filetypes = { "rust" } },
		gofmt = { conform = "gofmt", filetypes = { "go" } },
		goimports = { conform = "goimports", filetypes = { "go" } },
	},

	-- CoC: language -> extensions to install (we’ll filter by langs.lua)
	coc_by_lang = {
		lua = { "coc-sumneko-lua" },
		bash = { "coc-sh" },
		python = { "coc-pyright" },
		javascript = { "coc-tsserver" },
		typescript = { "coc-tsserver" },
		json = { "coc-json" },
		toml = { "coc-toml" },
		yaml = { "coc-yaml" },
		sql = {},
		php = { "coc-phpls" },
		c = { "coc-clangd" },
		cpp = { "coc-clangd" },
		rust = { "coc-rust-analyzer" },
		html = { "coc-html" },
		css = { "coc-css" },
		markdown = {},
		go = { "coc-go" },
		java = { "coc-java" },
		kotlin = {},
	},

	extras = { "rg" }, -- ripgrep for Telescope
	hints = {
		stylua = "pacman -S --needed stylua",
		shfmt = "pacman -S --needed shfmt",
		isort = "pacman -S --needed python-isort",
		black = "pacman -S --needed python-black",
		prettier = "pacman -S --needed nodejs npm && npm i -g prettier",
		jq = "pacman -S --needed jq",
		taplo = "pacman -S --needed taplo",
		yamlfmt = "pacman -S --needed go && go install github.com/google/yamlfmt/cmd/yamlfmt@latest",
		sqlfluff = "pip install --user sqlfluff",
		phpcbf = "pacman -S --needed php-code-sniffer",
		["clang-format"] = "pacman -S --needed clang",
		rustfmt = "rustup component add rustfmt",
		gofmt = "pacman -S --needed go  # included with Go",
		goimports = "go install golang.org/x/tools/cmd/goimports@latest",
		rg = "pacman -S --needed ripgrep",
	},
}
