alias deckaliases='nvim $ZDOTDIR/deck.d/01-deck_aliases.zsh'
alias paru='paru -r $USERROOT --config $USERROOT/etc/pacman.conf --gpgdir $USERROOT/etc/pacman.d/gnupg'
alias pacman='pacman -r $USERROOT --config $USERROOT/etc/pacman.conf --gpgdir $USERROOT/etc/pacman.d/gnupg'
alias p='paru -r $USERROOT --config $USERROOT/etc/pacman.conf --gpgdir $USERROOT/etc/pacman.d/gnupg'
alias pr='paru -r $USERROOT --config $USERROOT/etc/pacman.conf --gpgdir $USERROOT/etc/pacman.d/gnupg -Rns'
alias pro='paru -r $USERROOT --config $USERROOT/etc/pacman.conf --gpgdir $USERROOT/etc/pacman.d/gnupg -Rns $(pacman -Qtdq)'
alias protontricks='flatpak run com.github.Matoking.protontricks'
