#!/bin/sh
set -e
if   command -v paru    >/dev/null 2>&1; then paru -Syu
elif command -v pacman  >/dev/null 2>&1; then sudo pacman -Syu
elif command -v apt-get >/dev/null 2>&1; then sudo apt-get update && sudo apt-get full-upgrade -y
elif command -v dnf     >/dev/null 2>&1; then sudo dnf upgrade -y
elif command -v apk     >/dev/null 2>&1; then sudo apk upgrade; fi
rustup update
cargo install-update -a
