#!/bin/sh
# sets Xresouces colors. Pick a file in ~/.colors and it will write it to xcolors.
ls ~/.colors | grep -v xcolors | dmenu -l 30 | xargs -I {} cat ~/.colors/'{}' > ~/.colors/xcolors && xrdb ~/.Xresources
